//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormTB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FormTB()
        {
            this.EmployeeTB = new HashSet<EmployeeTB>();
        }
    
        public int FormID { get; set; }
        public int EmployeeID { get; set; }
        public string CompanyName { get; set; }
        public string Region { get; set; }
        public string City { get; set; }
        public string Benefits { get; set; }
        public string WorkingDays { get; set; }
        public string Gender { get; set; }
        public int TypeID { get; set; }
        public System.DateTime RequestDtae { get; set; }
        public string FormText { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeTB> EmployeeTB { get; set; }
    }
}
