

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DataLayer
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class OnlineJobEntities : DbContext
{
    public OnlineJobEntities()
        : base("name=OnlineJobEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<CommentTB> CommentTB { get; set; }

    public virtual DbSet<EmployeeTB> EmployeeTB { get; set; }

    public virtual DbSet<EmployerTB> EmployerTB { get; set; }

    public virtual DbSet<JobCategoryTB> JobCategoryTB { get; set; }

    public virtual DbSet<ResumeTB> ResumeTB { get; set; }

    public virtual DbSet<RoleTB> RoleTB { get; set; }

    public virtual DbSet<SelectedJobTB> SelectedJobTB { get; set; }

    public virtual DbSet<UserTB> UserTB { get; set; }

    public virtual DbSet<ResumeFormTB> ResumeFormTB { get; set; }

    public virtual DbSet<FormTB> FormTB { get; set; }

}

}

