//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SelectedJobTB
    {
        public int JobID { get; set; }
        public int EmployeeID { get; set; }
        public string JobDescription { get; set; }
    
        public virtual JobCategoryTB JobCategoryTB { get; set; }
        public virtual EmployeeTB EmployeeTB { get; set; }
    }
}
