//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTB
    {
        public int UserID { get; set; }
        public string UserName { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> EmployerID { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public int RoleID { get; set; }
        public Nullable<int> CommentID { get; set; }
    
        public virtual EmployeeTB EmployeeTB { get; set; }
        public virtual EmployerTB EmployerTB { get; set; }
        public virtual RoleTB RoleTB { get; set; }
    }
}
